"""
data_generation.py
==================
Generates synthetic Hebrew PTSD-indicator dataset via an LLM pipeline.

Public symbols re-exported for downstream consumers (run_pipeline):
    LLMProvider, LLMConfig, LLMClient, OllamaClient, OpenRouterClient,
    OpenAIClient, MockLLMClient, ResilienceLLMClient, create_llm_client,
    DatasetScenario, DatasetExample, DatasetPromptBuilder, generate_dataset
"""

from __future__ import annotations

import abc
import enum
import json
import logging
import os
import random
import re
import urllib.request
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# DSM-5 Clinical Grounding — Hebrew linguistic markers per symptom cluster
# Extracted from: "זיהוי סימפטומים של PTSD בשיח.docx" (clinical mapping document)
# These are HARDCODED — never generated by LLM at runtime.
# ---------------------------------------------------------------------------

DSM5_CRITERIA: dict[str, dict] = {
    "intrusive_memories": {
        "cluster": "B",
        "criteria": ["B1", "B2", "B3", "B4", "B5"],
        "definition_en": "Recurrent involuntary intrusive memories, traumatic nightmares, dissociative flashbacks, or intense distress/physiological reactions to trauma cues",
        "hebrew_markers": [
            "פתאום חוזרים לי קטעים לראש",
            "ריח מסוים ישר מחזיר אותי לשם",
            "שוב אני שם",
            "קטעים שלא יוצאים מהראש",
            "נכנס לי לראש",
            "חוזר על עצמו בחלומות",
            "כאילו זה קורה עכשיו",
        ],
        "hebrew_slang": [
            "בלאקאאוט",
            "מתנתק",
            "נסחף",
        ],
        "linguistic_patterns": [
            "historical present — past events narrated in present tense",
            "first-person singular density (אני, אותי, שלי)",
            "sensory detail density (sight, smell, sound, touch)",
            "sudden topic shift mid-sentence without logical connector",
        ],
    },
    "avoidance": {
        "cluster": "C",
        "criteria": ["C1", "C2"],
        "definition_en": "Persistent avoidance of distressing trauma-related thoughts/feelings (C1) and external reminders — people, places, situations (C2)",
        "hebrew_markers": [
            "לא פותח חדשות יותר",
            "עשיתי עיקוף שלם כדי לא לעבור שם",
            "לא בא לי לדבר על זה",
            "מנסה לא לחשוב על זה",
            "מסיח דעת מהכל",
            "לא מגיע לשם",
            "לא יכול להיות שם",
        ],
        "hebrew_slang": [
            "עיקוף",
            "להתחמק",
            "לכבות את המוח",
        ],
        "linguistic_patterns": [
            "topic shifting — abrupt change away from charged subject",
            "omission — conspicuous absence of trauma-related content",
            "decreased cognitive-processing words (מכיוון ש, אני חושב, הבנתי)",
            "logistical cancellation language (מבטל, לא מגיע, סיבה אחרת)",
        ],
    },
    "emotional_numbing": {
        "cluster": "D",
        "criteria": ["D5", "D6", "D7"],
        "definition_en": "Markedly diminished interest in activities (D5); feelings of detachment/estrangement from others (D6); persistent inability to experience positive emotions (D7)",
        "hebrew_markers": [
            "מרגיש מנותק מהכל",
            "ידעתי שאני אמור לשמוח אבל שום דבר לא זז בפנים",
            "קיר זכוכית",
            "כמו מחוץ לסרט",
            "ריק בפנים",
            "אין לי טעם לכלום",
            "הם לא מבינים",
        ],
        "hebrew_slang": [
            "בועה",
            "מנותק",
            "קפוא",
        ],
        "linguistic_patterns": [
            "shift from plural pronouns (אנחנו) to singular (אני) — loss of collective identity",
            "barrier metaphors — קיר זכוכית, עולם מקביל, בועה",
            "emotional incongruence — positive context with flat or absent response",
            "decreased emotional expressives — no exclamation marks, no positive emoji",
        ],
    },
    "guilt_shame": {
        "cluster": "D",
        "criteria": ["D3", "D4"],
        "definition_en": "Persistent distorted self-blame or blame of others for the trauma (D3); persistent negative emotional states — guilt, shame (D4)",
        "hebrew_markers": [
            "הייתי צריך לפעול אחרת",
            "הייתי חייב לעצור את זה",
            "אסור היה לי",
            "מה היה קורה אילו",
            "אוכל את עצמי",
            "לא מצליח לסלוח לעצמי",
            "זה האשמתי",
        ],
        "hebrew_slang": [
            "אוכל את עצמי",
            "מכרסם בי",
            "לועס את עצמי",
        ],
        "linguistic_patterns": [
            "counterfactual thinking — מה היה קורה אילו, אילו רק",
            "deontic modality past tense — הייתי צריך, הייתי חייב, אסור היה",
            "cognitive rumination — circular re-examination of events",
            "absolute self-directed blame without qualification",
        ],
    },
    "anger_irritability": {
        "cluster": "E",
        "criteria": ["E1", "E2"],
        "definition_en": "Irritable behavior and angry outbursts (E1); reckless or self-destructive behavior (E2)",
        "hebrew_markers": [
            "מתעצבן מכל שטות",
            "הכל מעלה לי את הסעיף",
            "מתפוצץ על כולם",
            "לא מצליח לשלוט בעצמי",
            "מתפרק על חבר'ה",
            "כעסתי בלי סיבה",
        ],
        "hebrew_slang": [
            "על הסעיף",
            "להימחק",
            "להתפרק",
            "להישרף",
            "מתפוצץ",
        ],
        "linguistic_patterns": [
            "expressive punctuation anomalies — ?!?!, ALL CAPS, excessive exclamation marks",
            "anger lexicon density — כעס, תסכול, שנאה, עוינות",
            "disproportionate reaction to minor trigger",
            "self-destructive behavior language — מסוכן, מסכן, לא אכפת לי מה יקרה",
        ],
    },
    "hypervigilance": {
        "cluster": "E",
        "criteria": ["E3", "E4"],
        "definition_en": "Hypervigilance — heightened threat-scanning alertness (E3); exaggerated startle response to sudden sounds or movements (E4)",
        "hebrew_markers": [
            "יושב תמיד עם הגב לקיר",
            "סורק את החדר כשנכנס",
            "קופץ מכל טריקת דלת",
            "פתאום רעש וכבר קפצתי",
            "לא מצליח להירגע",
            "בודק את הסביבה",
            "חרד מכל רחש",
        ],
        "hebrew_slang": [
            "דרוך",
            "גב לקיר",
            "מחווט",
            "על הקצה",
        ],
        "linguistic_patterns": [
            "tactical/military spatial language in civilian contexts",
            "environmental scanning verbs — בודק, סורק, מחפש, מאתר",
            "startle pattern — פתאום + physical-startle verb + acoustic trigger",
            "interpersonal suspicion — questioning others' motives without evidence",
        ],
    },
    "functional_impairment": {
        "cluster": "D+E",
        "criteria": ["D1", "E5"],
        "definition_en": "Inability to recall key aspects of the trauma — dissociative amnesia (D1); difficulty concentrating — cognitive fog (E5)",
        "hebrew_markers": [
            "ערפל מוחי",
            "אני לא בטוח אם",
            "יכול להיות ש",
            "לא מצליח להתרכז",
            "לא מצליח לסיים משימה",
            "הראש שלי לא עובד",
            "חסרות לי חתיכות בפאזל",
        ],
        "hebrew_slang": [
            "ערפל מוחי",
            "ראש ריק",
            "לא בראש",
        ],
        "linguistic_patterns": [
            "epistemic uncertainty markers — אני לא בטוח, יכול להיות, אולי",
            "memory gap markers — לא זוכר, חתיכות חסרות, מטושטש",
            "readability degradation — fragmented sentences, topic drift, repetitions",
            "verification questions to others — זה קרה ככה?, נכון?",
        ],
    },
    "sleep_disturbance": {
        "cluster": "E",
        "criteria": ["E6"],
        "definition_en": "Sleep disturbance — difficulty falling or staying asleep, unrefreshing sleep (not nightmares; nightmares are B2)",
        "hebrew_markers": [
            "לילה לבן",
            "המוח שלי לא נכבה",
            "לא ישנתי יומיים",
            "ישנתי שעתיים השבוע",
            "כל רחש בבית מעיר אותי",
            "שוכב במיטה עייף אבל לא נרדם",
            "מנוע שלא נכבה",
        ],
        "hebrew_slang": [
            "לילה לבן",
            "זומבי",
            "מיובש",
        ],
        "linguistic_patterns": [
            "binary sleep failure — ישנתי/לא ישנתי with extreme time quantifiers",
            "brain-as-engine metaphor — מנוע שלא נכבה, אי אפשר לכבות",
            "time quantifiers of deprivation — לא ישנתי X ימים/שעות",
            "late-night posting timestamp is a strong metadata signal",
        ],
    },
}

# ---------------------------------------------------------------------------
# LLM Abstraction Layer
# ---------------------------------------------------------------------------

class LLMProvider(enum.Enum):
    GEMINI = "gemini"
    OLLAMA = "ollama"
    OPENROUTER = "openrouter"
    OPENAI = "openai"


@dataclass
class LLMConfig:
    provider: LLMProvider = LLMProvider.GEMINI
    model_name: str = "gemini-1.5-flash"
    api_key: str | None = None
    base_url: str | None = None
    fallback_enabled: bool = True
    allow_paid_apis: bool = False
    timeout: int = 60


class LLMClient(abc.ABC):
    @abc.abstractmethod
    def generate(self, prompt: str) -> str: ...

    @abc.abstractmethod
    def health_check(self) -> bool: ...

    def switch_provider(self, provider: LLMProvider) -> "LLMClient":
        return _build_client(LLMConfig(provider=provider))


class GeminiClient(LLMClient):
    def __init__(self, config: LLMConfig) -> None:
        self._config = config
        self._model_name = config.model_name or "gemini-1.5-flash"
        self._api_key = config.api_key or os.environ.get("GEMINI_API_KEY", "")

    def _extract_text(self, response: object) -> str:
        # Try the canonical response.text first, then fallback to candidate parts.
        text = getattr(response, "text", None)
        if isinstance(text, str) and text.strip():
            return text.strip()
        candidates = getattr(response, "candidates", None)
        if not candidates:
            return ""
        parts: list[str] = []
        for cand in candidates:
            content = getattr(cand, "content", None)
            if content is None:
                continue
            for part in getattr(content, "parts", []) or []:
                ptxt = getattr(part, "text", None)
                if isinstance(ptxt, str) and ptxt.strip():
                    parts.append(ptxt.strip())
        return "\n".join(parts).strip()

    def generate(self, prompt: str) -> str:
        import time as _time
        if not self._api_key:
            raise RuntimeError("GEMINI_API_KEY is not set.")
        try:
            import google.generativeai as genai
        except Exception as exc:
            raise RuntimeError(
                "google-generativeai is not installed. Install it with: pip install google-generativeai"
            ) from exc

        genai.configure(api_key=self._api_key)
        model = genai.GenerativeModel(self._model_name)
        _t0 = _time.time()
        try:
            response = model.generate_content(
                prompt,
                generation_config={
                    "temperature": 0.75,
                    "max_output_tokens": 120,
                },
                request_options={"timeout": self._config.timeout},
            )
            text = self._extract_text(response)
            if not text:
                raise RuntimeError("Gemini returned an empty response.")
            logger.debug("[gemini:generate] %.2fs", _time.time() - _t0)
            return text
        except Exception as exc:
            msg = str(exc)
            if "429" in msg or "quota" in msg.lower() or "rate" in msg.lower():
                raise RuntimeError(f"Gemini quota/rate error: {msg}") from exc
            if "timeout" in msg.lower() or "deadline" in msg.lower():
                raise RuntimeError(f"Gemini timeout error: {msg}") from exc
            raise RuntimeError(f"Gemini API error: {msg}") from exc

    def health_check(self) -> bool:
        return bool(self._api_key)


class OllamaClient(LLMClient):
    def __init__(self, config: LLMConfig) -> None:
        self._config = config
        self._base_url = (config.base_url or "http://localhost:11434").rstrip("/")
        self._model = config.model_name or "llama3"

    def generate(self, prompt: str) -> str:
        import time as _time
        url = f"{self._base_url}/api/generate"
        payload = json.dumps(
            {"model": self._model, "prompt": prompt, "stream": False,
             "options": {
                 "temperature": 0.75,
                 # Safety cap — stop sequences below handle early exit in practice.
                 "num_predict": 120,
                 "num_ctx": 2048,
                 "num_gpu": 999,
             },
             # llama3 end-of-turn / end-of-text tokens.
             # Ollama stops as soon as any of these appear instead of grinding
             # to num_predict. Output is ~40-70 tokens; this saves 50-80 tokens
             # of wasted generation per call (~2-3 seconds each).
             "stop": ["<|eot_id|>", "<|end_of_text|>", "\n\n\n"],
             }
        ).encode()
        req = urllib.request.Request(
            url, data=payload, headers={"Content-Type": "application/json"}
        )
        _t0 = _time.time()
        with urllib.request.urlopen(req, timeout=self._config.timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        _elapsed = _time.time() - _t0
        _eval_count = data.get("eval_count", 0)
        _tps = _eval_count / max(data.get("eval_duration", 1) / 1e9, 0.001)
        logger.debug("[ollama:generate] %.2fs | %d tokens | %.1f tok/s",
                     _elapsed, _eval_count, _tps)
        return data.get("response", "")

    def health_check(self) -> bool:
        try:
            urllib.request.urlopen(
                f"{self._base_url}/api/tags", timeout=5
            )
            return True
        except Exception:
            return False


class OpenRouterClient(LLMClient):
    _DEFAULT_BASE = "https://openrouter.ai/api/v1"
    _DEFAULT_MODEL = "mistralai/mistral-7b-instruct:free"

    def __init__(self, config: LLMConfig) -> None:
        self._config = config
        self._api_key = config.api_key or os.environ.get("OPENROUTER_API_KEY", "")
        self._base_url = (config.base_url or self._DEFAULT_BASE).rstrip("/")
        self._model = config.model_name or self._DEFAULT_MODEL

    def generate(self, prompt: str) -> str:
        if not self._api_key:
            raise RuntimeError("OPENROUTER_API_KEY is not set.")
        payload = json.dumps(
            {"model": self._model, "messages": [{"role": "user", "content": prompt}]}
        ).encode()
        req = urllib.request.Request(
            f"{self._base_url}/chat/completions",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self._api_key}",
            },
        )
        with urllib.request.urlopen(req, timeout=self._config.timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return data["choices"][0]["message"]["content"]

    def health_check(self) -> bool:
        return bool(self._api_key)


class OpenAIClient(LLMClient):
    _DEFAULT_BASE = "https://api.openai.com/v1"
    _DEFAULT_MODEL = "gpt-3.5-turbo"

    def __init__(self, config: LLMConfig) -> None:
        if not config.allow_paid_apis:
            raise RuntimeError(
                "OpenAI client is disabled by default. "
                "Set allow_paid_apis=True in LLMConfig to enable."
            )
        self._config = config
        self._api_key = config.api_key or os.environ.get("OPENAI_API_KEY", "")
        self._base_url = (config.base_url or self._DEFAULT_BASE).rstrip("/")
        self._model = config.model_name or self._DEFAULT_MODEL

    def generate(self, prompt: str) -> str:
        if not self._api_key:
            raise RuntimeError("OPENAI_API_KEY is not set.")
        payload = json.dumps(
            {"model": self._model, "messages": [{"role": "user", "content": prompt}]}
        ).encode()
        req = urllib.request.Request(
            f"{self._base_url}/chat/completions",
            data=payload,
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self._api_key}",
            },
        )
        with urllib.request.urlopen(req, timeout=self._config.timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        return data["choices"][0]["message"]["content"]

    def health_check(self) -> bool:
        return bool(self._api_key)


class MockLLMClient(LLMClient):
    _HEBREW_RESPONSES: list[str] = [
        "כמעט לא ישנתי הלילה. שוב. קמתי באמצע הלילה ופשוט לא הצלחתי לחזור לישון.",
        "אני לא יודע איך להסביר את זה, אני פשוט לא מצליח להירגע. כל רעש קטן מקפיץ אותי.",
        "מאז שחזרתי מהמילואים אני מרגיש כאילו אני לא באמת כאן. כאילו הכל קורה מסביבי ואני בכלל לא חלק מזה.",
        "אני פשוט לא מסוגל להגיע לשם. אני יודע שאני צריך, אבל הגוף שלי פשוט מסרב. מעדיף לעשות עיקוף של עשרים דקות.",
        "הכל בסדר. קצת עייף. לא יודע, יש לי המון דברים בראש, אין לי כוח לדבר על זה עכשיו.",
        "פתאום באמצע הארוחה נזכרתי במשהו, ולא הצלחתי להמשיך לאכול. פשוט יצאתי החוצה לנשום אוויר.",
        "אני כבר לא זוכר מתי פעם אחרונה לא הייתי דרוך ככה. כל פעם שאני נכנס לחדר, אני קודם כל סורק אותו.",
        "חזרתי מהבסיס לפני שבועיים. אבל עוד לא באמת חזרתי.",
    ]



    def __init__(self, config: LLMConfig | None = None) -> None:
        self._config = config

    def generate(self, prompt: str) -> str:
        idx = abs(hash(prompt)) % len(self._HEBREW_RESPONSES)
        return self._HEBREW_RESPONSES[idx]

    def health_check(self) -> bool:
        return True


def _build_client(config: LLMConfig) -> LLMClient:
    if config.provider == LLMProvider.GEMINI:
        return GeminiClient(config)
    if config.provider == LLMProvider.OLLAMA:
        return OllamaClient(config)
    if config.provider == LLMProvider.OPENROUTER:
        return OpenRouterClient(config)
    if config.provider == LLMProvider.OPENAI:
        return OpenAIClient(config)
    raise ValueError(f"Unknown provider: {config.provider}")


class ResilienceLLMClient(LLMClient):
    """Wraps a primary LLMClient with free-first automatic fallback."""

    def __init__(self, config: LLMConfig) -> None:
        self._config = config
        self._primary = _build_client(config)
        self._fallback_chain: list[LLMClient] = self._build_fallback_chain(config)

    def _build_fallback_chain(self, config: LLMConfig) -> list[LLMClient]:
        chain: list[LLMClient] = []
        if os.environ.get("GEMINI_API_KEY") and config.provider != LLMProvider.GEMINI:
            chain.append(GeminiClient(LLMConfig(provider=LLMProvider.GEMINI)))
        if (
            os.environ.get("OPENROUTER_API_KEY")
            and config.provider != LLMProvider.OPENROUTER
        ):
            chain.append(
                OpenRouterClient(LLMConfig(provider=LLMProvider.OPENROUTER))
            )
        return chain

    def generate(self, prompt: str) -> str:
        if not self._config.fallback_enabled:
            return self._primary.generate(prompt)
        candidates = [self._primary] + self._fallback_chain
        last_error: Exception = RuntimeError("No LLM providers are available.")
        for client in candidates:
            try:
                return client.generate(prompt)
            except Exception as exc:
                last_error = exc
        return f"[LLM ERROR] All providers failed. Last error: {last_error}"

    def health_check(self) -> bool:
        return self._primary.health_check()

    def switch_provider(self, provider: LLMProvider) -> "ResilienceLLMClient":
        new_config = LLMConfig(
            provider=provider,
            model_name=self._config.model_name,
            api_key=self._config.api_key,
            base_url=self._config.base_url,
            fallback_enabled=self._config.fallback_enabled,
            allow_paid_apis=self._config.allow_paid_apis,
            timeout=self._config.timeout,
        )
        return ResilienceLLMClient(new_config)


def create_llm_client(
    provider: LLMProvider = LLMProvider.GEMINI,
    model_name: str = "gemini-1.5-flash",
    api_key: str | None = None,
    base_url: str | None = None,
    fallback_enabled: bool = True,
    allow_paid_apis: bool = False,
    mock: bool = False,
) -> LLMClient:
    if mock:
        return MockLLMClient()
    config = LLMConfig(
        provider=provider,
        model_name=model_name,
        api_key=api_key,
        base_url=base_url,
        fallback_enabled=fallback_enabled,
        allow_paid_apis=allow_paid_apis,
    )
    return ResilienceLLMClient(config)


# ---------------------------------------------------------------------------
# Dataset Generation Pipeline
# ---------------------------------------------------------------------------

CONTEXT_BANK: list[str] = [
    "מאז שחזרתי מהמילואים", "בחודשים האחרונים", "מאז כל הסיפור", "מאז התקופה בעזה", "לאחרונה",
    "אני שם לב ש", "מאז שחזרתי הביתה", "מאז שהשתחררתי מהצו", "בימים האחרונים", "מאז שחזרנו מהקו",
    "מהרגע שהורדתי את המדים", "בזמן האחרון", "מאז שכל הבלגן התחיל", "מאז ה-7 באוקטובר", "מאז התקופה בצפון",
    "כל פעם שאני נזכר במילואים", "מאז שחזרתי לשגרה", "מאז שיצאנו משם", "מאז שנגמר הסבב", "בתקופה האחרונה",
    "מאז שחזרתי לעבודה", "מאז הצו שמונה האחרון", "כל פעם שאני לבד", "מאז שהיינו שם בפנים",
    "מאז שחזרתי למציאות", "בשבועות האחרונים", "מאז שחזרתי ללימודים", "מאז שכל זה נגמר",
    "מאז שחזרתי למשפחה", "כל פעם שאני יוצא מהבית", "מאז שחזרתי לישון במיטה שלי", "מאז שחזרתי מהסבב האחרון",
]

BEHAVIOR_BANKS: dict[str, list[str]] = {
    "sleep_disturbance": [
        "לא מצליח לישון רצוף", "מתעורר מכל רעש קטן", "נרדם רק לפנות בוקר", "מתעורר עם דפיקות לב בלילה",
        "בוהה בתקרה שעות לפני שנרדם", "מתעורר באמצע הלילה ספוג בזיעה", "לא מצליח להירדם בלי טלוויזיה דולקת",
        "מפחד ללכת לישון לפעמים", "נרדם בקושי ומתעורר אחרי שעה", "מרגיש שגם כשאני ישן אני לא באמת נח",
        "קם כל כמה שעות לבדוק שהכל בסדר", "ישן ממש מעט שעות בלילה", "מתהפך במיטה עד הבוקר",
        "לא מצליח לעצום עיניים", "השינה שלי נהייתה ממש גרועה", "נרדם רק מול המחשב",
        "מתעורר בבהלה מכל שטות", "חלומות מוזרים מפריעים לי לישון", "הלילות הפכו להיות סיוט",
        "הגוף שלי עייף אבל המוח לא נרדם",
    ],
    "hypervigilance": [
        "קופץ מכל טריקת דלת", "תמיד מחפש איפה היציאה", "לא מצליח להירגע במקומות סגורים",
        "כל רעש חזק מקפיץ אותי", "סורק את כל האנשים מסביב ברחוב", "יושב תמיד עם הגב לקיר",
        "מרגיש דרוך כל הזמן בלי סיבה", "כל אופנוע שעובר נשמע לי כמו התרעה", "בודק את הדלת עשר פעמים לפני שאני נכנס",
        "כל רעש של זיקוקים מלחיץ אותי", "לא יכול לשבת במקומות הומים", "מרגיש שאני חייב להיות מוכן לכל תרחיש",
        "קופץ כשאנשים נוגעים בי מאחורה", "מסתכל לצדדים כל הזמן כשאני הולך ברחוב", "מרגיש שהגוף שלי במתח מתמיד",
        "כל טריקה של חלון נשמעת לי כמו בום", "לא מסוגל להוריד את המגננות", "דרוך כאילו אני עדיין בעמדה",
        "מחפש מחסה אוטומטית כשיש רעש פתאומי", "מרגיש שהאדרנלין לא יורד",
    ],
    "avoidance": [
        "לא פותח חדשות יותר", "נמנע מלנסוע לשם", "מחליף נושא ישר כשמדברים על זה", "הפסקתי ללכת למפגשי צוות",
        "לא יכול לראות סרטי מלחמה", "מתרחק מכל מה שמזכיר לי את התקופה ההיא", "פשוט לא רוצה לדבר על המילואים",
        "נמנע מלפגוש חברים מהצבא", "הפסקתי לעבור ברחוב שבו זה קרה", "מתעלם מהודעות בקבוצה של הפלוגה",
        "בורח מכל סיטואציה שיכולה להזכיר לי", "מעדיף לא לצאת מהבית כדי לא לשמוע סיפורים",
        "סוגר את הרדיו כשיש שירים של המלחמה", "לא מסוגל להסתכל על תמונות מהתקופה הזאת",
        "מתחמק משאלות של אנשים על מה שהיה", "שיניתי את הדרך הביתה כדי לא לעבור ליד הבסיס",
        "מנסה להדחיק הכל ולא לחשוב על זה", "נמנע מכל קשר עם הצבא עכשיו", "לא הולך לאזכרות או טקסים",
        "פשוט חוסם את כל מה שקשור לזה",
    ],
    "intrusive_memories": [
        "פתאום חוזרים לי קטעים לראש", "ריח מסוים ישר מחזיר אותי לשם", "רואה תמונות משם כשאני עוצם עיניים",
        "המראות משם לא עוזבים אותי", "פתאום אני מוצא את עצמי שוב בתוך האירוע", "הקולות משם מהדהדים לי בראש",
        "זיכרונות פשוט צפים בלי שליטה", "מרגיש כאילו אני שוב שם לרגע", "ריח של שריפה מקפיץ לי זיכרונות",
        "תמונות מהלחימה רצות לי בראש", "פתאום משום מקום הכל חוזר אליי", "המחשבות עוקבות אחריי לכל מקום",
        "רואה את הפנים שלהם מול העיניים שלי", "זה מרגיש חי מדי בראש שלי", "קשה לי להוציא את התמונות האלה מהראש",
        "הזיכרונות משם ממש מוחשיים לי", "כל דבר קטן מזכיר לי את מה שראיתי", "מרגיש שהמלחמה רצה לי בראש בלופ",
        "המחשבות על מה שהיה שם רודפות אותי", "פלאשבקים של דברים שקרו שם",
    ],
    "anger_irritability": [
        "מתעצבן מכל שטות", "אין לי סבלנות לאנשים", "מתפוצץ על הילדים בלי סיבה", "הכל מעלה לי את הסעיף",
        "מרגיש עצבני כל הזמן", "צועק על אנשים בכביש בלי הפסקה", "כל דבר קטן שמישהו אומר מרתיח אותי",
        "איבדתי את הסבלנות לכל העולם", "נהייתי תוקפני כלפי הסביבה שלי", "מתעצבן כששואלים אותי מה נשמע",
        "רב עם חברים על דברים מטופשים", "מרגיש שהדם שלי רותח בקלות", "כל ויכוח קטן הופך לפיצוץ",
        "פשוט אין לי כוח לשמוע אף אחד", "נהייתי ממש קצר עם בת הזוג שלי", "התגובות שלי נהיו ממש קיצוניות",
        "כל שטות בעבודה מוציאה אותי מדעתי", "מרגיש כעס פנימי שלא משתחרר", "מתעצבן על דברים שפעם לא הפריעו לי",
        "קשה לי לשלוט בעצבים שלי לאחרונה",
    ],
    "emotional_numbing": [
        "מרגיש מנותק מהכל", "לא באמת מתרגש מכלום", "מרגיש קצת ריק בפנים", "הכל נראה לי חסר משמעות עכשיו",
        "לא מצליח להרגיש שמחה", "מרגיש כמו רובוט שפשוט פועל", "התחושות שלי פשוט נעלמו",
        "לא מרגיש קרוב לאף אחד יותר", "קשה לי להרגיש אהבה או חום", "הכל נראה לי אפור ושטוח",
        "כבר לא נהנה מדברים שאהבתי", "מרגיש כאילו אני צופה בחיים מהצד", "הרגשות שלי פשוט קפאו",
        "לא מצליח להתחבר לאף אחד", "מרגיש אדישות להכל", "כאילו יש לי חומת אבן סביב הלב",
        "שום דבר לא באמת נוגע בי יותר", "מרגיש ריחוק מהמשפחה והחברים", "הכל מרגיש לי רחוק וזר",
        "איבדתי את היכולת להתרגש",
    ],
    "guilt_shame": [
        "לא מפסיק לחשוב מה הייתי יכול לעשות אחרת", "מרגיש לא בסדר עם עצמי", "אוכל את עצמי על דברים שקרו שם",
        "מרגיש רע שאני פה והם עדיין שם", "למה אני חזרתי והוא לא", "מרגיש אשם על זה שאני מנסה לחזור לשגרה",
        "משהו שם מרגיש לי לא פתור", "מרגיש שלא עשיתי מספיק בשביל הצוות", "מסתכל במראה ולא מזהה את עצמי",
        "מפחד שאנשים ידעו מה באמת עשינו שם", "מרגיש שהייתי צריך להיות יותר חזק", "אשם על זה שאני חי ונהנה",
        "מרגיש בושה על דברים שחשבתי עליהם שם", "אוכל את עצמי על החלטות שקיבלתי", "מרגיש רע עם זה שעזבתי אותם",
        "למה יצאתי לפני כולם", "מרגיש שמשהו בי נהרס שם", "אשם על זה שקשה לי עכשיו",
        "מרגיש שאני לא ראוי לכל הטוב הזה", "האשמה פשוט לא מרפה ממני",
    ],
    "functional_impairment": [
        "לא מצליח להתרכז בעבודה", "כבר אין לי כוח לאנשים", "שוכח דברים בסיסיים כל הזמן",
        "לא מצליח לעשות כלום בבית", "בוהה במסך שעות בלי לעשות כלום", "קשה לי לקבל החלטות פשוטות",
        "מרגיש שהראש שלי לא עובד כמו פעם", "לא מצליח לנהל שיחה רגילה", "כל משימה קטנה נראית לי הר",
        "הפסקתי לתפקד כמו שצריך", "מוצא את עצמי פשוט בוהה בקיר", "לא מצליח לחזור לקצב של העבודה",
        "שוכח פגישות ודברים חשובים", "אין לי מוטיבציה לכלום", "מרגיש שכל פעולה דורשת ממני המון כוח",
        "קשה לי לשבת על הלימודים", "הזנחתי את כל התחביבים שלי", "לא מצליח להחזיק סדר יום נורמלי",
        "כל הזמן מאחר לכל מקום", "מרגיש שהחיים שלי נעצרו",
    ],
}

NEGATIVE_BEHAVIOR_BANK: list[str] = [
    "המילואים האלה גמרו אותי מעייפות", "הרסר שוב דפק אותנו עם התורנויות", "אין לי כוח לעוד צו 8 בזמן הקרוב",
    "הציוד שקיבלנו היה פשוט פח", "נמאס לי לישון בשקי שינה", "האוכל בבסיס היה פשוט נוראי",
    "שוב אין תקציב לנסיעות של המילואים", "נשרף לי כל הקיץ על המילואים האלה",
    "המענק של המילואים עדיין לא נכנס לחשבון", "הבוס שלי עושה לי פרצופים על המילואים",
    "הפסדתי המון חומר בלימודים בגלל הצו", "התנאים בשטח היו פשוט זוועה", "נמאס לי מהבירוקרטיה של המערכת",
    "הקצינה שוב שכחה לחתום לי על הטפסים", "שוב פעם מקפיצים אותנו לאימון מיותר",
    "אין לי כוח לשמירות האלה יותר", "התבאסתי רצח שלא הייתי ביומולדת של הבת שלי",
    'הפסדתי טיסה לחו"ל בגלל הצו המטומטם הזה', "שוב פעם המדים האלה מלאים בחול",
    "היה חם רצח ואין מזגן באוהל", "נמאס לי מהפקקים בדרך לבסיס", 'החמ"ל הזה זה המקום הכי משעמם בעולם',
    "שוב פעם אכלנו לוף כל השבוע", "הנעליים הצבאיות גמרו לי את הרגליים", "היה קו קשה אבל לפחות נגמר",
    "התגעגעתי בטירוף לאוכל של הבית", "השירותים בבסיס זה הדבר הכי מגעיל שיש",
    "נמאס לי מהצעקות של המפקד", "כל היום רק חיכינו וחיכינו לשוברים",
    "למה תמיד המילואימניקים מקבלים את הציוד הישן", "הפסדתי מלא כסף מהעסק בגלל הסבב הזה",
]

TONE_BANK: dict[str, list[str]] = {
    "restrained": ["בשקט", "בלי להגזים", "לא יודע להסביר", "בקטע מוזר", "פשוט ככה"],
    "tired": ["אין לי כוח לזה", "אני גמור", "תשוש מהכל", "פשוט עייף", "בלי אנרגיות"],
    "cynical": ["כרגיל", "מה חדש", "אותו סיפור", "איזה יופי", "ממש חגיגה"],
    "frustrated": ["זה פשוט לא הגיוני", "כבר נמאס לי", "זה מעצבן ברמות", "חלאס", "אי אפשר ככה"],
    "detached": ["לא יודע", "וואלה", "משהו כזה", "בערך", "לא ממש משנה"],
}

SENTENCE_STARTERS: list[str] = [
    "אני שם לב ש", "לא יודע למה אבל", "בזמן האחרון", "מאז שחזרתי", "פתאום קלטתי ש",
    "וואלה", "תכלס", "בכנות", "שמעו", "משהו עובר עליי", "אני מרגיש ש", "יש לי קטע כזה ש",
    "בקיצור", "האמת ש", "קשה לי עם זה ש", "אני מוצא את עצמי", "לא מזמן קרה ש",
    "הקטע הוא ש", "בכלל לא חשבתי ש", "בלי קשר לכלום", "פשוט", "מסתבר ש",
    "איכשהו", "נראה לי ש", "זה התחיל כש",
]

SENTENCE_ENDINGS: list[str] = [
    "וזה מתחיל להפריע לי", "ולא ממש שמתי לב לזה עד עכשיו", "ואין לי מושג למה",
    "וזה פשוט ככה", "משהו הזוי", "וזהו בגדול", "וזה פשוט לא עובר",
    "אני כבר לא יודע מה לעשות", "וזה קורה כל הזמן", "כבר התרגלתי לזה לצערם של כולם",
    "וזה די מפחיד אותי", "משהו שאי אפשר להסביר", "וזה פשוט תקוע לי בראש",
    "וזה הכי מעצבן שיש", "ככה זה נראה כרגע", "וזה לא משתנה", "וזה ממש מוזר לי",
    "פשוט ככה", "וזהו", "משהו שם נשבר", "וזה פשוט מלווה אותי", "ואני לא רואה לזה סוף",
    "וזה קצת מלחיץ אותי", "וזה לא עוזב אותי", "כאילו זה חלק ממני עכשיו",
]

MILITARY_SLANG_BANK: list[str] = [
    'צו 8', 'חמ"ל', "שמירה", "קו", "עמדה", "צוות", "פלוגה", "מילואים", "סדיר", "ווסט",
    'נגמ"ש', "מדים", "בסיס", "מפקד", "קשר", "אימון", "שטח", "סבב", "כוננות", "משימה",
    "חוליה", "גדוד", "מחלקה", "נקודת מפגש",
]

AMBIGUOUS_BANK: list[str] = [
    "אני קצת אחר מאז", "קשה לי להסביר", "משהו בי השתנה", "הכל נראה אחרת פתאום",
    "אני לא אותו אדם", "דברים פשוט מרגישים אחרת", "קשה לי לחזור לעצמי",
    "אני מנסה להבין מה קורה לי", "משהו פשוט לא אותו דבר", "אני בתקופה קצת מוזרה",
    "קשה לשים על זה את האצבע", "התחושה הזאת לא עוזבת", "אני מרגיש שמשהו השתבש",
    "הכל נהיה קצת כבד", "אני לא מצליח להשתחרר מזה", "זה פשוט יושב עליי",
    "משהו שם בתקופה ההיא עשה לי משהו", "אני פשוט לא מוצא את המקום שלי",
    "דברים קטנים נהיו מסובכים", "משהו בתחושה הכללית לא בסדר",
]

_DATASET_FORBIDDEN_TERMS: list[str] = [
    "PTSD", "פוסט טראומה", "אבחון", "הפרעה", "diagnosis", "disorder",
    "post trauma", "psychiatric",
]

_HARD_NEGATIVE_THEMES: list[str] = [
    "exhaustion from reserve duty schedule, no PTSD indicators",
    "frustration with military bureaucracy and logistics only",
    "physical tiredness from long guard shifts, not psychological",
    "annoyance at poor planning by commanders",
    "boredom from base routine, missing family",
    "anger about poor equipment or living conditions at the base",
    "missing family while on miluim, otherwise fine",
    "complaints about food and organization at the base",
    "fatigue from lack of sleep due only to guard duty schedule",
]

_AMBIGUOUS_THEMES: list[str] = [
    "vague emotional discomfort, unclear if normal stress or more",
    "borderline restlessness after reserve duty, ambiguous interpretation",
    "difficulty concentrating — could be work pressure or something more",
    "vague unease about returning to certain places, reason unclear",
    "mild irritability that could be tiredness or something deeper",
]

_POSITIVE_COMBOS: list[list[str]] = [
    ["sleep_disturbance"],
    ["hypervigilance"],
    ["avoidance"],
    ["anger_irritability"],
    ["intrusive_memories"],
    ["emotional_numbing"],
    ["functional_impairment"],
    ["guilt_shame"],
    ["sleep_disturbance", "hypervigilance"],
    ["sleep_disturbance", "intrusive_memories"],
    ["anger_irritability", "guilt_shame"],
    ["avoidance", "emotional_numbing"],
    ["hypervigilance", "avoidance"],
    ["functional_impairment", "emotional_numbing"],
    ["sleep_disturbance", "anger_irritability"],
    ["guilt_shame", "intrusive_memories"],
    ["sleep_disturbance", "hypervigilance", "avoidance"],
    ["anger_irritability", "functional_impairment", "guilt_shame"],
]

_POSITIVE_WEIGHTS: list[int] = [
    5, 5, 4, 4, 2, 2, 2, 1,
    4, 2, 2, 2, 2, 1, 1, 1,
    1, 1,
]


@dataclass
class DatasetExample:
    id: str
    text: str
    labels: list[str]
    example_type: str
    platform: str
    explicitness: str
    severity: str
    slang_used: list[str]
    dsm5_criterion: str = ""  # DSM-5 sub-criterion code(s) that grounded this example
    synthetic: bool = True


@dataclass
class DatasetScenario:
    labels: list[str]
    example_type: str
    platform: str
    explicitness: str
    severity: str
    slang_level: str
    include_military_context: bool
    theme_hint: str = ""
    dsm5_criterion: str = ""  # filled by _pick_dsm5_criterion() before prompt build


def _detect_slang(text: str) -> list[str]:
    return [term for term in MILITARY_SLANG_BANK if term in text]


def _pick_dsm5_criterion(labels: list[str], example_type: str) -> str:
    """Return DSM-5 criterion code+summary string for the primary label of this example."""
    if not labels or example_type == "hard_negative":
        return ""
    for label in labels:
        entry = DSM5_CRITERIA.get(label)
        if entry:
            codes = "+".join(entry["criteria"])
            summary = entry["definition_en"][:65]
            return f"{codes}: {summary}"
    return ""


def _dsm5_markers_hint(labels: list[str], example_type: str) -> str:
    """Build a DSM-5 Hebrew marker injection string for the generation prompt."""
    if not labels or example_type in ("hard_negative",):
        return ""
    for label in labels:
        entry = DSM5_CRITERIA.get(label)
        if entry:
            markers_str = ", ".join(f'"{m}"' for m in entry["hebrew_markers"][:4])
            slang_line = (
                "\n  Optional slang: " + ", ".join(f'"{s}"' for s in entry["hebrew_slang"][:2])
                if entry["hebrew_slang"] else ""
            )
            return (
                f"DSM-5 CLINICAL GROUNDING ({'+'.join(entry['criteria'])}):\n"
                f"  Weave 1-2 of these natural Hebrew expressions into the text: {markers_str}"
                + slang_line
                + "\n\n"
            )
    return ""


def _plan_scenarios() -> list[DatasetScenario]:
    platforms = ["whatsapp", "reddit", "tweet", "diary"]

    def pick_combo() -> list[str]:
        return list(random.choices(_POSITIVE_COMBOS, weights=_POSITIVE_WEIGHTS, k=1)[0])

    scenarios: list[DatasetScenario] = []

    for _ in range(35):
        scenarios.append(DatasetScenario(
            labels=pick_combo(),
            example_type="positive_clear",
            platform=random.choice(platforms),
            explicitness=random.choice(["explicit", "behavioral", "behavioral"]),
            severity=random.choice(["medium", "strong", "strong"]),
            slang_level=random.choice(["low", "medium", "high"]),
            include_military_context=random.random() > 0.25,
        ))

    for _ in range(25):
        scenarios.append(DatasetScenario(
            labels=pick_combo(),
            example_type="implicit",
            platform=random.choice(platforms),
            explicitness="implicit",
            severity=random.choice(["mild", "medium"]),
            slang_level=random.choice(["medium", "high"]),
            include_military_context=random.random() > 0.3,
        ))

    for _ in range(25):
        scenarios.append(DatasetScenario(
            labels=[],
            example_type="hard_negative",
            platform=random.choice(platforms),
            explicitness=random.choice(["explicit", "behavioral"]),
            severity=random.choice(["mild", "medium"]),
            slang_level=random.choice(["low", "medium", "high"]),
            include_military_context=True,
            theme_hint=random.choice(_HARD_NEGATIVE_THEMES),
        ))

    for _ in range(15):
        labels = pick_combo() if random.random() > 0.4 else []
        scenarios.append(DatasetScenario(
            labels=labels,
            example_type="ambiguous",
            platform=random.choice(platforms),
            explicitness="implicit",
            severity="mild",
            slang_level=random.choice(["medium", "high"]),
            include_military_context=random.random() > 0.4,
            theme_hint=random.choice(_AMBIGUOUS_THEMES),
        ))

    random.shuffle(scenarios)
    return scenarios


_FEW_SHOT_EXEMPLARS: dict[str, list[str]] = {
    "sleep_disturbance": [
        "מאז שחזרתי אני לא מצליח לישון ברצף. כל רעש קטן בבית מעיר אותי.",
        "שוב שלוש בלילה. לא יודע למה, אבל אני מסוגל להירדם בכל מקום חוץ מבמיטה שלי.",
        "אמרתי לאשתי שהכל בסדר, אבל כבר שבוע שאני מתעורר בארבע בבוקר ולא מצליח לחזור לישון.",
        "הראש פשוט לא נכבה בלילה. שוכב במיטה ומחכה שיגיע הבוקר.",
    ],
    "hypervigilance": [
        "אני כבר עושה את זה אוטומטית - כל מקום שאני נכנס אליו, אני ישר מחפש את היציאה.",
        "ישבנו במסעדה ולא הצלחתי להפסיק לבדוק מי נכנס ויוצא. אשתי שמה לב לזה עוד לפניי.",
        "כל טריקת דלת מקפיצה אותי. אני יודע שזה טיפשי, אבל הגוף פשוט לא מקשיב.",
        "אני תמיד מתיישב עם הגב לקיר. אפילו לא מתכוון לזה, זה פשוט קורה.",
    ],
    "avoidance": [
        "אין לי כוח לראות חדשות יותר. זה ישר עושה לי כבד בראש.",
        "עשיתי היום עיקוף שלם רק כדי לא לעבור ליד הצומת ההוא.",
        "הזמינו אותי למפגש פלוגה. תירצתי שיש לי תוכניות אחרות.",
        "יש מקומות שאני פשוט כבר לא הולך אליהם. אי אפשר להסביר למה.",
    ],
    "intrusive_memories": [
        "פתאום באמצע הארוחה זה קפץ לי לראש, ולא הצלחתי להמשיך לאכול. פשוט יצאתי החוצה לנשום.",
        "הריח של הדלק החזיר אותי לשם ולא הצלחתי להמשיך לנהוג כמה דקות.",
        "לפעמים אני באמצע שיחה ופתאום הראש פשוט עף לשם. אנשים לא מבינים את זה.",
        "יש זיכרון ספציפי שפשוט צף לי פתאום, בלי אזהרה. תמיד ברגעים הכי לא מתאימים.",
    ],
    "anger_irritability": [
        "בזמן האחרון אני מתפוצץ משטויות. הבן שלי שפך קצת מיץ ואיבדתי את זה לגמרי. זה ממש לא מתאים לי.",
        "אין לי סבלנות לכלום, פשוט אפס. אני לא יודע מה עובר עליי.",
        "אני קולט שכולם מסביבי הולכים על ביצים, וזה עושה לי הרגשה נוראית.",
        "אני מתפרץ על אנשים ואחר כך אוכל את עצמי מרוב חרטה. אני פשוט לא מצליח לשלוט בזה.",
    ],
    "emotional_numbing": [
        "מאז שחזרתי מהמילואים אני מרגיש מנותק. הכל קורה מסביבי ואני פשוט לא חלק מזה.",
        "הייתי בחתונה של חבר טוב. בראש שמחתי בשבילו, אבל בפנים לא הרגשתי כלום.",
        "כולם מספרים בדיחות ואני צוחק כי זה מה שמצופה. אבל בפנים הכל ריק.",
        "אני פיזית שם, אבל לא באמת נוכח. לא יודע איך להסביר את זה אחרת.",
    ],
    "guilt_shame": [
        "יש דברים שפשוט לא מדברים עליהם. אתה מבין שחייבים להמשיך הלאה, אבל משהו מזה נשאר איתך.",
        "כולם אומרים שעשינו את מה שהיינו צריכים לעשות, אבל אני עדיין חוזר לזה בראש.",
        "הייתי בטוח שזה יעבור עם הזמן, אבל זה פשוט לא משחרר.",
        "אי אפשר להסביר את זה למי שלא היה שם. ואני גם לא בטוח שאני רוצה לנסות.",
    ],
    "functional_impairment": [
        "חזרתי לעבודה אבל אני לא באמת שם. יכול לשבת יום שלם מול המסך ובסוף אין לי מושג מה עשיתי.",
        "אמא שלי שאלה אם הכל בסדר. אמרתי לה שכן, אבל ראיתי שהיא לא קונה את זה.",
        "אני לא מצליח לסיים אפילו משימות פשוטות. מתחיל, עוזב באמצע, שוכח מזה לגמרי.",
        "אפילו לסדר את הבית נהיה פרויקט בשבילי. אני פשוט לא מצליח להביא את עצמי להתחיל.",
    ],
    "hard_negative": [
        "עייף מת. לעלות לשמור כל לילה זה פשוט סיוט.",
        "המפקד שלנו לא יודע לארגן כלום. חיכינו שלוש שעות לאוטובוס שבכלל לא הגיע.",
        "אין קליטה, האוכל על הפנים וקפוא בלילות. חוויית מילואים קלאסית.",
        "קפאתי מקור כל הלילה בעמדה. שמישהו יסביר לי איך זה הגיוני באמצע מאי?",
        "מתגעגע הביתה. עוד שבוע כזה ואני בחוץ.",
    ],
    "ambiguous": [
        "הכל בסדר, סתם קצת עייף. לא יודע, יש לי המון דברים בראש ואין לי כוח לדבר על זה עכשיו.",
        "חזרתי מהבסיס לפני שבועיים, אבל עוד לא באמת חזרתי לעצמי.",
        "קצת קשה עכשיו, אבל יעבור.",
        "לא יודע, בזמן האחרון אני פחות מרגיש כמו עצמי. אולי זה סתם מעייפות.",
    ],
}

_SITUATION_MAP: dict[str, list[str]] = {
    "sleep_disturbance": [
        "The person can't sleep well. They wake up at night and can't fall back asleep. Their mind won't shut off.",
        "Since returning from reserve duty, sleep is broken. Night after night, awake at odd hours for no clear reason.",
        "The person lies awake for hours. Tired all day but can't sleep when it matters.",
    ],
    "hypervigilance": [
        "The person finds themselves constantly scanning their surroundings without meaning to. Every sudden sound startles them.",
        "The person can't fully relax in public. They automatically position themselves to see the room and exits.",
        "Every small noise makes the person tense or jump. They're constantly alert in a way that's exhausting.",
    ],
    "avoidance": [
        "The person is avoiding certain places, routes, or topics without fully explaining why to anyone.",
        "The person can't bring themselves to watch the news or go back to certain locations.",
        "There are places the person just doesn't go anymore. They take longer routes. They change the subject.",
    ],
    "intrusive_memories": [
        "In the middle of ordinary moments, something triggers a memory and the person is suddenly somewhere else mentally.",
        "The person keeps getting pulled back to moments they didn't choose. Smells, sounds, random things trigger it.",
        "Specific memories come back without warning, breaking concentration at the worst times.",
    ],
    "anger_irritability": [
        "The person has been losing their temper over small things lately — things that never used to bother them.",
        "The person snaps at people around them and regrets it. They can't explain why everything irritates them.",
        "Patience is gone. The person reacts too strongly to minor frustrations and knows it but can't stop.",
    ],
    "emotional_numbing": [
        "The person feels emotionally flat. Present physically but disconnected from what's happening around them.",
        "The person notices they don't react the way they used to. Things that would have moved them don't anymore.",
        "There's a hollow quality to how the person experiences things. Like watching life from a distance.",
    ],
    "guilt_shame": [
        "The person carries something they can't easily explain to others. A weight that doesn't go away.",
        "The person keeps returning to decisions made under pressure. Wondering if they could have done differently.",
        "There's a sense of responsibility the person can't shake — being okay when others weren't.",
    ],
    "functional_impairment": [
        "The person is struggling to function at their usual level. Work, daily tasks, social life all feel harder.",
        "The person is withdrawing. Can't concentrate. Basic things are piling up and they can't get started.",
        "Functioning has dropped noticeably. Going through the motions but not really there.",
    ],
}

_NEGATIVE_SITUATION_POOL: list[str] = [
    "The person is physically exhausted from guard duty shifts and the reserve duty schedule — normal military fatigue, nothing more.",
    "The person is frustrated by poor logistics, bad planning, and disorganized commanders — annoyed but otherwise fine.",
    "The person is complaining about the food, equipment, boredom, and missing home — typical reservist venting.",
    "The person is tired, missing family, counting down the days. Completely normal reservist feelings, no deeper issues.",
    "The person is angry at bureaucracy and wasted time on base — a typical complaint about reserve duty inefficiency.",
]

_AMBIGUOUS_SITUATION_POOL: list[str] = [
    "The person mentions something vague — a feeling of being off, not quite themselves. Cause is unclear.",
    "The person is restless and a bit disconnected, but doesn't name why. Could be fatigue, could be something else.",
    "There's mild discomfort the person doesn't fully articulate. The reader can't be sure of the source.",
    "Something feels slightly wrong, but the person downplays it. The emotional signal is present but deniable.",
]


class DatasetPromptBuilder:
    _PLATFORM_BRIEF: dict[str, str] = {
        "whatsapp": "WhatsApp message to a close friend or family. Short, casual, informal — like real texting.",
        "reddit": "Reddit post or comment on an Israeli forum. Semi-anonymous, slightly longer, candid.",
        "tweet": "Tweet or X post. Very short, punchy, unfiltered.",
        "diary": "Personal diary entry. First-person, private, unguarded thoughts.",
    }

    def build(self, scenario: DatasetScenario) -> str:
        situation = self._get_situation(scenario)
        examples = self._get_examples(scenario)
        platform = self._PLATFORM_BRIEF.get(scenario.platform, self._PLATFORM_BRIEF["whatsapp"])
        slang_note = (
            "You may use 1-2 natural Hebrew military terms if they fit organically (e.g. מילואים, בסיס, עמדה)."
            if scenario.include_military_context and random.random() > 0.5
            else "Do NOT force military vocabulary — only include it if it sounds completely natural."
        )
        # Inject Hebrew markers from DSM5_CRITERIA — hardcoded from clinical mapping document
        dsm5_block = _dsm5_markers_hint(scenario.labels, scenario.example_type)
        return (
            "You are generating realistic synthetic Hebrew text for NLP research.\n\n"
            "TASK: Write 2-4 short sentences in natural Israeli Hebrew.\n\n"
            f"SITUATION: {situation}\n\n"
            + dsm5_block
            + f"FORMAT: {platform}\n\n"
            "STYLE RULES:\n"
            "  - Write like a real Israeli person — not a translator, not a writer\n"
            "  - Use simple, everyday spoken Hebrew (not formal, not literary)\n"
            "  - Keep sentences short and natural, like real speech or texting\n"
            "  - No dramatic language, no poetic phrasing, no exaggeration\n"
            "  - No clinical vocabulary whatsoever\n"
            f"  - {slang_note}\n"
            "  - Output Hebrew ONLY — no English letters anywhere in the text\n"
            "  - Never use: PTSD, פוסט טראומה, אבחון, הפרעה, disorder\n"
            "  - Do NOT start output with '---', '--', or any punctuation prefix\n"
            "  - Use only real Hebrew words — no invented or garbled vocabulary\n\n"
            "EXAMPLES OF THE CORRECT STYLE:\n"
            + "\n".join(f'"{ex}"' for ex in examples)
            + "\n\nBEFORE OUTPUTTING — verify: (1) zero English letters, "
            "(2) no '---' prefix, (3) only real Hebrew words, "
            "(4) sounds like a real Israeli wrote it.\n\n"
            "NOW WRITE THE TEXT (Hebrew only, 2-4 sentences, nothing else):"
        )

    def _get_situation(self, scenario: DatasetScenario) -> str:
        if scenario.example_type == "hard_negative":
            return random.choice(_NEGATIVE_SITUATION_POOL)
        if scenario.example_type == "ambiguous":
            base = random.choice(_AMBIGUOUS_SITUATION_POOL)
            if scenario.labels:
                label = random.choice(scenario.labels)
                hints = _SITUATION_MAP.get(label, [])
                if hints:
                    hint = random.choice(hints)
                    base = f"{base} Very faint hint toward: {hint[:70]}. Keep it deniable and indirect."
            return base
        parts: list[str] = []
        for label in scenario.labels:
            opts = _SITUATION_MAP.get(label, [])
            if opts:
                parts.append(random.choice(opts))
        if not parts:
            return "The person is having a hard time lately without naming the reason clearly."
        combined = " ".join(parts[:2])
        if scenario.explicitness == "implicit":
            combined += " Express this indirectly — the reader should infer the difficulty, not be told it."
        return combined

    def _get_examples(self, scenario: DatasetScenario) -> list[str]:
        pool: list[str] = []
        if scenario.example_type == "hard_negative":
            pool = list(_FEW_SHOT_EXEMPLARS.get("hard_negative", []))
        elif scenario.example_type == "ambiguous":
            pool = list(_FEW_SHOT_EXEMPLARS.get("ambiguous", []))
        else:
            for label in scenario.labels:
                pool.extend(_FEW_SHOT_EXEMPLARS.get(label, []))
        if not pool:
            pool = [
                "מאז שחזרתי אני לא באמת ישן רצוף. כל רעש קטן בבית מעיר אותי.",
                "הכל בסדר. עייף קצת. לא יודע, המון דברים בראש.",
                "אני מתפוצץ על שטויות בזמן האחרון. זה לא אני.",
            ]
        random.shuffle(pool)
        return pool[:3]


def _pick_slang_injection() -> str | None:
    roll = random.random()
    if roll < 0.80:
        return None
    pool = MILITARY_SLANG_BANK[:]
    if roll < 0.95:
        return random.choice(pool)
    return f"{random.choice(pool)} ו{random.choice(pool)}"


_SLANG_PERIOD_TERMS: set[str] = {"מילואים", "סדיר", "סבב", "קו", "אימון", "המבצע", "התקופה", "צו 8", "מעצר", "הכנות", "מסדר", "שבוז", "קאדר", "שחור", "שבצק", "נשבר"}

_SUBJECT_NOUNS: set[str] = {
    "השינה", "הלילות", "החלומות", "הזיכרונות", "המחשבות", "הקולות",
    "האשמה", "הגוף", "התחושות", "התגובות", "הרגשות", "הזיכרונות",
}

_INTERROGATIVES: set[str] = {"למה", "איך", "מה", "איפה", "מתי"}


def _behavior_shape(phrase: str) -> str:
    # Return "clause" if phrase has its own subject or is a question; else "verb".
    s = phrase.strip()
    first = s.split()[0] if s else ""
    if first in _SUBJECT_NOUNS:
        return "clause"
    # Definite-noun subjects: starts with ה + ends with common plural/fem suffix
    if (first.startswith("ה") and len(first) > 3
            and any(first.endswith(suf) for suf in ("ים", "ות", "ה", "ן"))):
        return "clause"
    if first in _INTERROGATIVES:
        return "clause"
    return "verb"


def _compose_positive_clause(context: str, behavior: str) -> str:
    # Choose the right glue between context opener and behavior phrase.
    if _behavior_shape(behavior) == "clause":
        return f"{context} {behavior}."
    return f"{context} אני {behavior}."


def _apply_slang_to_sentences(sentences: list[str], slang: str, context: str) -> None:
    # Avoid "מאז {slang} — מאז …" collision; avoid non-period slang in temporal prefix.
    if context.startswith("מאז") or slang not in _SLANG_PERIOD_TERMS:
        sentences.append(f"({slang} — בלי קשר.)")
    else:
        sentences.insert(0, f"מאז {slang} —")


def _safe_tone_tail(tone_word: str) -> str:
    # Short tone words need a framing wrapper to stand alone as a sentence.
    if len(tone_word) < 6:
        return f"זה {tone_word}."
    return f"{tone_word}."


def _assemble_positive(labels: list[str], explicitness: str) -> str:
    context = random.choice(CONTEXT_BANK)
    sentences: list[str] = []
    chosen_labels = labels[:2] if len(labels) > 1 else labels
    behaviors: list[str] = []
    for label in chosen_labels:
        bank = BEHAVIOR_BANKS.get(label, [])
        if bank:
            behaviors.append(random.choice(bank))
    if not behaviors:
        behaviors = ["מרגיש לא בסדר"]
    tone_key = random.choice(list(TONE_BANK.keys()))
    tone_word = random.choice(TONE_BANK[tone_key])
    if explicitness == "implicit":
        starter = random.choice(SENTENCE_STARTERS)
        ending = random.choice(SENTENCE_ENDINGS)
        first_clause = _compose_positive_clause(context, behaviors[0])
        sentences.append(f"{starter} {first_clause}")
        if len(behaviors) > 1:
            sentences.append(f"{behaviors[1]}. {ending}.")
        else:
            sentences.append(f"{ending}.")
    else:
        sentences.append(_compose_positive_clause(context, behaviors[0]))
        if len(behaviors) > 1:
            b1 = behaviors[1]
            if _behavior_shape(b1) == "clause":
                sentences.append(f"{b1}.")
            else:
                sentences.append(f"בנוסף, {b1}.")
        sentences.append(_safe_tone_tail(tone_word))
    slang = _pick_slang_injection()
    if slang:
        _apply_slang_to_sentences(sentences, slang, context)
    return " ".join(sentences)


def _assemble_hard_negative() -> str:
    behaviors = random.sample(NEGATIVE_BEHAVIOR_BANK, k=random.randint(1, 3))
    tone_key = random.choice(["tired", "cynical", "frustrated"])
    tone_word = random.choice(TONE_BANK[tone_key])
    sentences = [f"{b}." for b in behaviors]
    sentences.append(_safe_tone_tail(tone_word))
    slang = _pick_slang_injection()
    if slang:
        sentences.append(f"({slang} — זה החיים.)")
    return " ".join(sentences)


def _assemble_ambiguous(labels: list[str]) -> str:
    context = random.choice(CONTEXT_BANK)
    ambiguous_phrase = random.choice(AMBIGUOUS_BANK)
    tone_word = random.choice(TONE_BANK["detached"] + TONE_BANK["restrained"])
    sentences = [f"{context}, {ambiguous_phrase}."]
    if labels:
        bank = BEHAVIOR_BANKS.get(random.choice(labels), [])
        if bank:
            subtle = random.choice(bank)
            sentences.append(f"אולי זה בגלל ש{subtle}, לא בטוח.")
    sentences.append(_safe_tone_tail(tone_word))
    return " ".join(sentences)


_POLISH_REJECT_PATTERNS: list[str] = [
    "(תרגום", "(translation", "(כתובה", "ניסיוני לשמור", "שכתוב:", "פלט עברית",
    "\u05be",  # maqaf used heavily in niqqud contexts
]

_NIQQUD_RANGE = (0x05B0, 0x05C7)  # Hebrew vowel points


def _has_niqqud(text: str) -> bool:
    return any(_NIQQUD_RANGE[0] <= ord(c) <= _NIQQUD_RANGE[1] for c in text)


# Structural defects the LLM should fix; reject polished output if still present.
_BROKEN_SYNTAX_PATTERNS: list[re.Pattern[str]] = [
    re.compile("אני ה[א-ת]{2,}"),            # "אני" + definite-noun subject
    re.compile("אני (למה|איך|מה|איפה|מתי)"),  # "אני" + interrogative
    re.compile("מאז.{0,40}—\\s*מאז"),         # duplicate "מאז" within ~40 chars
    re.compile("(בערך|וואלה|כרגיל)[.\\s]*$"), # dangling short-tone tail
]


def _has_broken_syntax(text: str) -> bool:
    # Return True if any known structural defect is present in text.
    return any(p.search(text) is not None for p in _BROKEN_SYNTAX_PATTERNS)


def _polish_quality_ok(raw: str, polished: str) -> bool:
    """Return True only if polished is a safe improvement over raw."""
    if len(polished) < 15:
        return False
    # Must contain Hebrew letters
    he_count = sum(1 for c in polished if "\u05D0" <= c <= "\u05EA")
    if he_count < 10:
        return False
    # Reject niqqud (biblical/formal register)
    if _has_niqqud(polished):
        return False
    # Reject if LLM meta-text leaked in
    lower = polished.lower()
    for pat in _POLISH_REJECT_PATTERNS:
        if pat.lower() in lower:
            return False
    # Reject if polished lost too much content (< 30% of raw word count, loosened to allow restructuring)
    raw_words = len(raw.split())
    pol_words = len(polished.split())
    if raw_words > 3 and pol_words < raw_words * 0.3:
        return False
    # Reject if it got dramatically longer (LLM added content)
    if pol_words > raw_words * 2.5:
        return False
    # Reject archaic forms
    archaic = ["אינני", "אינו", "הנני", "הנה כי כן", "אמנם כי"]
    if any(a in polished for a in archaic):
        return False
    # Reject if structural defects survived the polish pass
    if _has_broken_syntax(polished):
        return False
    return True


# ---------------------------------------------------------------------------
# Generation constants
# ---------------------------------------------------------------------------

# Checkpoint frequency: write partial results every N examples to prevent total loss on crash.
_CHECKPOINT_INTERVAL: int = 200

# Maximum fraction of samples that may share the same 3-word context opener.
# Computed relative to TARGET (3000) to avoid repetitive sentence starts.
_MAX_SAME_PREFIX_FRACTION: float = 0.10


def _postprocess_llm_output(raw_result: str, raw_text: str) -> str:
    """
    Shared post-processing applied to every LLM-generated polish candidate.

    Strips surrounding quotes, removes meta-commentary lines that start with '(',
    normalises whitespace, and falls back to the original text if quality check fails.
    """
    result = raw_result.strip()
    if len(result) >= 2 and result[0] in ('"', "'", "\u201c") and result[-1] in ('"', "'", "\u201d"):
        result = result[1:-1].strip()
    lines = [ln for ln in result.splitlines() if not ln.strip().startswith("(")]
    result = " ".join(" ".join(ln.split()) for ln in lines if ln.strip()).strip()
    if _polish_quality_ok(raw_text, result):
        return result
    return raw_text


def _polish_with_few_shot(
    llm: LLMClient,
    raw_text: str,
    scenario: "DatasetScenario",
    builder: "DatasetPromptBuilder",
) -> str:
    # Build a rich few-shot prompt so the LLM rewrites raw_text in authentic Hebrew style.
    base_prompt = builder.build(scenario)
    prompt = (
        base_prompt
        + "\n\n---\nNOW: Rewrite the DRAFT below as ONE coherent Israeli Hebrew message in the style shown above.\n"
        "- Keep the overall meaning and emotional content.\n"
        "- You ARE allowed to restructure sentences to fix broken grammar.\n"
        "- Fix these specific defects if present: 'אני ה...' before a noun, 'אני למה/איך/מה', duplicate 'מאז … — מאז', "
        "or a two-word standalone tail like 'בערך.' or 'וואלה.'.\n"
        "- Output ONLY the rewritten Hebrew text — no explanations, no English, no quotes.\n\n"
        f"DRAFT:\n{raw_text}"
    )
    try:
        return _postprocess_llm_output(llm.generate(prompt), raw_text)
    except Exception as exc:
        logger.debug("few-shot polish failed, using raw text: %s", exc)
        return raw_text


def generate_dataset(llm: LLMClient, output_path: str = "dataset.json") -> list[DatasetExample]:
    from src.config import STRAT_SEED as _GEN_SEED
    random.seed(_GEN_SEED)
    TARGET = 2000
    PLAN = [
        ("positive_clear", 700),
        ("implicit", 500),
        ("hard_negative", 500),
        ("ambiguous", 300),
    ]

    def pick_combo() -> list[str]:
        return list(random.choices(_POSITIVE_COMBOS, weights=_POSITIVE_WEIGHTS, k=1)[0])

    platforms = ["whatsapp", "reddit", "tweet", "diary"]
    # Builder provides few-shot exemplar anchoring for the polish step.
    _builder = DatasetPromptBuilder()
    examples: list[DatasetExample] = []
    seen: set[str] = set()
    context_prefix_count: dict[str, int] = {}
    MAX_SAME_PREFIX = max(1, int(TARGET * _MAX_SAME_PREFIX_FRACTION))

    def accept(text: str) -> bool:
        if len(text) < 25:
            return False
        hebrew = sum(1 for c in text if "\u05D0" <= c <= "\u05EA")
        if hebrew < 12:
            return False
        tl = text.lower()
        for term in _DATASET_FORBIDDEN_TERMS:
            if term.lower() in tl:
                return False
        # Reject leaked meta-text
        for pat in _POLISH_REJECT_PATTERNS:
            if pat.lower() in tl:
                return False
        # Reject niqqud (biblical register)
        if _has_niqqud(text):
            return False
        # Reject archaic forms
        archaic = ["אינני", "אינו", "הנני"]
        if any(a in text for a in archaic):
            return False
        # Reject sentences cut mid-thought (ends with "בתוך." "מתוך." etc.)
        stripped = text.rstrip(" .")
        dangling = ["בתוך", "מתוך", "בתוך-", "לתוך"]
        if any(stripped.endswith(d) for d in dangling):
            return False
        # Reject structural grammar defects
        if _has_broken_syntax(text):
            return False
        norm = " ".join(text.split()).lower()
        if norm in seen:
            return False
        return True

    for example_type, count in PLAN:
        generated = 0
        attempts = 0
        while generated < count and attempts < count * 8:
            attempts += 1
            labels: list[str] = []
            explicitness = "explicit"
            severity = "medium"

            slang_level = "medium"
            include_military_context = random.random() > 0.3

            if example_type == "positive_clear":
                labels = pick_combo()
                explicitness = random.choice(["explicit", "behavioral"])
                severity = random.choice(["medium", "strong"])
                slang_level = random.choice(["low", "medium", "high"])
                raw = _assemble_positive(labels, explicitness)
            elif example_type == "implicit":
                labels = pick_combo()
                explicitness = "implicit"
                severity = random.choice(["mild", "medium"])
                slang_level = random.choice(["medium", "high"])
                raw = _assemble_positive(labels, explicitness)
            elif example_type == "hard_negative":
                labels = []
                explicitness = "explicit"
                severity = "mild"
                slang_level = random.choice(["low", "medium"])
                include_military_context = True
                raw = _assemble_hard_negative()
            else:
                labels = pick_combo() if random.random() > 0.4 else []
                explicitness = "implicit"
                severity = "mild"
                slang_level = random.choice(["medium", "high"])
                raw = _assemble_ambiguous(labels)

            # Build a scenario so the polish step can inject few-shot exemplars.
            _scenario = DatasetScenario(
                labels=labels,
                example_type=example_type,
                platform=random.choice(platforms),
                explicitness=explicitness,
                severity=severity,
                slang_level=slang_level,
                include_military_context=include_military_context,
            )
            # Assign DSM-5 criterion — hardcoded from clinical mapping document
            _scenario.dsm5_criterion = _pick_dsm5_criterion(labels, example_type)
            # Give the LLM up to 3 passes to produce an acceptable rewrite.
            text = raw
            for _ in range(3):
                candidate = _polish_with_few_shot(llm, raw, _scenario, _builder)
                if accept(candidate):
                    text = candidate
                    break
            if not accept(text):
                continue

            # Enforce context-opener diversity
            prefix_key = " ".join(text.split()[:3])
            if context_prefix_count.get(prefix_key, 0) >= MAX_SAME_PREFIX:
                continue
            context_prefix_count[prefix_key] = context_prefix_count.get(prefix_key, 0) + 1

            norm = " ".join(text.split()).lower()
            seen.add(norm)
            examples.append(DatasetExample(
                id=f"syn_{len(examples):04d}",
                text=text,
                labels=labels,
                example_type=example_type,
                platform=_scenario.platform,  # match the register the text was written for
                explicitness=explicitness,
                severity=severity,
                slang_used=_detect_slang(text),
                dsm5_criterion=_scenario.dsm5_criterion,
                synthetic=True,
            ))
            generated += 1
            logger.info(
                "[%3d/%d] %-14s | dsm5=%-30s | labels=%s",
                len(examples), TARGET, example_type,
                _scenario.dsm5_criterion[:30] if _scenario.dsm5_criterion else "(none)",
                labels,
            )

            # Fault-tolerance: save a checkpoint every _CHECKPOINT_INTERVAL samples.
            if len(examples) % _CHECKPOINT_INTERVAL == 0:
                _checkpoint_path = Path(output_path).with_name("dataset.checkpoint.json")
                _checkpoint_records = [
                    {
                        "id": ex.id, "text": ex.text, "labels": ex.labels,
                        "example_type": ex.example_type, "platform": ex.platform,
                        "explicitness": ex.explicitness, "severity": ex.severity,
                        "slang_used": ex.slang_used, "dsm5_criterion": ex.dsm5_criterion,
                        "synthetic": ex.synthetic,
                    }
                    for ex in examples
                ]
                with _checkpoint_path.open("w", encoding="utf-8") as _cp_fh:
                    json.dump(_checkpoint_records, _cp_fh, ensure_ascii=False, indent=2)
                logger.info(
                    "Checkpoint saved: %d samples → %s",
                    len(examples), _checkpoint_path,
                )

    records = [
        {
            "id": ex.id, "text": ex.text, "labels": ex.labels,
            "example_type": ex.example_type, "platform": ex.platform,
            "explicitness": ex.explicitness, "severity": ex.severity,
            "slang_used": ex.slang_used, "dsm5_criterion": ex.dsm5_criterion,
            "synthetic": ex.synthetic,
        }
        for ex in examples
    ]
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
    logger.info("Saved %d examples → %s", len(records), output_path)
    return examples


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

# Import canonical path from config so run_pipeline.py and standalone use agree
from src.config import DATASET_OUTPUT_PATH  # noqa: E402


def main() -> None:
    if os.environ.get("GEMINI_API_KEY"):
        logger.info("GEMINI_API_KEY found — using Gemini model (gemini-1.5-flash).")
        llm = create_llm_client(
            provider=LLMProvider.GEMINI,
            model_name="gemini-1.5-flash",
        )
    elif os.environ.get("OPENROUTER_API_KEY"):
        logger.info("Gemini key not found — falling back to OpenRouter (free tier).")
        llm = create_llm_client(
            provider=LLMProvider.OPENROUTER,
            model_name="mistralai/mistral-7b-instruct:free",
        )
    else:
        logger.warning(
            "No LLM provider available (missing GEMINI_API_KEY and OPENROUTER_API_KEY). "
            "Falling back to MockLLMClient — outputs are deterministic fake Hebrew. "
            "Set GEMINI_API_KEY to generate real synthetic data."
        )
        llm = MockLLMClient()

    DATASET_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    examples = generate_dataset(llm, output_path=str(DATASET_OUTPUT_PATH))
    logger.info("Generated %d synthetic examples.", len(examples))


if __name__ == "__main__":
    main()
