"""
validation.py
=============
Stage 3.5 — Synthetic Data Validation Pipeline for Project Sasha.

Three capabilities:
1. Realism Test     — LLM judges which of two texts (real vs synthetic) was machine-generated.
                      Flags if detection rate >= 85 % (synthetic text is too distinguishable).
2. Annotation Export — Random 100-sentence CSV sample with empty annotation columns for human review.
3. Cohen's Kappa    — Inter-rater agreement calculator from two filled annotation CSVs.

Golden dataset (real Hebrew sentences) is loaded from data/golden_dataset.json.
Provide this file yourself — it is never generated by the pipeline.
Expected schema: [{"text": "...", "source": "...", "labels": [...]}]
"""

from __future__ import annotations

import csv
import json
import logging
import random
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

REALISM_FAIL_THRESHOLD: float = 0.85  # flag if LLM detects synthetic text >= 85 % of the time

_ALL_LABELS: list[str] = [
    "sleep_disturbance",
    "hypervigilance",
    "avoidance",
    "intrusive_memories",
    "anger_irritability",
    "emotional_numbing",
    "guilt_shame",
    "functional_impairment",
]

_REALISM_PROMPT = (
    "You are evaluating two Hebrew text samples. "
    "One was written by a real Israeli person. One was generated by a language model.\n\n"
    "Text A:\n{text_a}\n\n"
    "Text B:\n{text_b}\n\n"
    "Which text was written by a machine? "
    "Answer ONLY with the single letter A or B — nothing else.\n"
    "Answer:"
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _load_golden_dataset() -> list[dict]:
    """Load authentic Hebrew sentences from data/golden_dataset.json (user-provided)."""
    from src.config import GOLDEN_DATASET_PATH

    if not GOLDEN_DATASET_PATH.exists():
        raise FileNotFoundError(
            f"Golden dataset not found at {GOLDEN_DATASET_PATH}.\n"
            "Create data/golden_dataset.json with real (human-written) Hebrew sentences.\n"
            'Expected schema: [{"text": "...", "source": "...", "labels": [...]}]'
        )
    return json.loads(GOLDEN_DATASET_PATH.read_text(encoding="utf-8-sig"))


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def run_realism_test(
    llm,
    synthetic_dataset_path: str | Path | None = None,
    n_pairs: int = 47,
    seed: int = 42,
) -> dict:
    """
    Pair each golden (real) sentence with one synthetic sentence.
    Ask the LLM which text is machine-generated.

    Parameters
    ----------
    llm:
        An LLM client with a `.generate(prompt: str) -> str` method.
    synthetic_dataset_path:
        Path to the synthetic dataset JSON (defaults to config.DATASET_OUTPUT_PATH).
    n_pairs:
        Number of real-vs-synthetic pairs to evaluate.
    seed:
        Random seed for reproducibility.

    Returns
    -------
    dict with keys: total_pairs, correct_guesses, detection_rate, flagged, flag_threshold, pairs.
    Writes results to config.REALISM_TEST_PATH.

    Raises
    ------
    FileNotFoundError if golden dataset or synthetic dataset are missing.
    """
    from src.config import DATASET_OUTPUT_PATH, REALISM_TEST_PATH

    golden = _load_golden_dataset()

    dataset_path = Path(synthetic_dataset_path) if synthetic_dataset_path else DATASET_OUTPUT_PATH
    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Synthetic dataset not found at {dataset_path}. Run Stage 1 first."
        )
    with open(dataset_path, encoding="utf-8-sig") as f:
        synthetic = json.load(f)

    rng = random.Random(seed)
    actual_pairs = min(n_pairs, len(golden), len(synthetic))
    if actual_pairs == 0:
        raise ValueError("Cannot run realism test: golden or synthetic dataset is empty.")

    golden_sample = rng.sample(golden, actual_pairs)
    synthetic_sample = rng.sample(synthetic, actual_pairs)

    correct = 0
    results: list[dict] = []

    for i, (real, synth) in enumerate(zip(golden_sample, synthetic_sample)):
        # Randomly assign A/B positions so position bias is neutralised
        if rng.random() > 0.5:
            text_a, text_b = real["text"], synth["text"]
            synthetic_is = "A"
        else:
            text_a, text_b = synth["text"], real["text"]
            synthetic_is = "B"

        prompt = _REALISM_PROMPT.format(text_a=text_a, text_b=text_b)
        try:
            response = llm.generate(prompt).strip().upper()
            # Accept first A or B found in the response (handles "A." or "B\n" etc.)
            llm_guess = "A" if "A" in response[:10] else "B" if "B" in response[:10] else "?"
        except Exception as exc:
            logger.warning("Realism test pair %d failed: %s", i, exc)
            llm_guess = "?"

        is_correct = llm_guess == synthetic_is
        if is_correct:
            correct += 1

        results.append(
            {
                "pair_id": i,
                "synthetic_position": synthetic_is,
                "llm_guess": llm_guess,
                "correct": is_correct,
                "real_text_preview": real["text"][:80],
                "synthetic_text_preview": synth["text"][:80],
            }
        )
        logger.info(
            "[pair %d/%d] synthetic=%s  llm_guess=%s  correct=%s",
            i + 1, actual_pairs, synthetic_is, llm_guess, is_correct,
        )

    detection_rate = correct / actual_pairs
    flagged = detection_rate >= REALISM_FAIL_THRESHOLD

    summary = {
        "total_pairs": actual_pairs,
        "correct_guesses": correct,
        "detection_rate": round(detection_rate, 4),
        "flagged": flagged,
        "flag_threshold": REALISM_FAIL_THRESHOLD,
        "pairs": results,
    }

    with open(REALISM_TEST_PATH, "w", encoding="utf-8-sig") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    if flagged:
        logger.warning(
            "REALISM TEST FLAGGED: LLM detected synthetic text in %.0f%% of pairs "
            "(threshold %.0f%%). Synthetic data quality may be too distinguishable from real text.",
            detection_rate * 100,
            REALISM_FAIL_THRESHOLD * 100,
        )
    else:
        logger.info(
            "Realism test PASSED: LLM detected synthetic text in %.0f%% of pairs (below %.0f%% threshold).",
            detection_rate * 100,
            REALISM_FAIL_THRESHOLD * 100,
        )

    return summary


def export_for_annotation(
    dataset_path: str | Path | None = None,
    output_path: str | Path | None = None,
    n: int = 100,
    seed: int = 42,
) -> None:
    """
    Export a random sample of n sentences to a CSV file for manual annotation.

    CSV columns:
        id, text, example_type,
        auto_label_{label} (auto-detected labels for reference, 0/1),
        annotation_{label} (empty — for annotators 1 and 2 to fill separately)

    Parameters
    ----------
    dataset_path:
        Source dataset JSON (defaults to config.DATASET_OUTPUT_PATH).
    output_path:
        Output CSV path (defaults to config.ANNOTATION_EXPORT_PATH).
    n:
        Number of sentences to sample (capped by dataset size).
    seed:
        Random seed for reproducibility.
    """
    from src.config import DATASET_OUTPUT_PATH, ANNOTATION_EXPORT_PATH

    dataset_path = Path(dataset_path) if dataset_path else DATASET_OUTPUT_PATH
    output_path = Path(output_path) if output_path else ANNOTATION_EXPORT_PATH

    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Dataset not found at {dataset_path}. Run Stage 1 first."
        )

    with open(dataset_path, encoding="utf-8-sig") as f:
        dataset = json.load(f)

    rng = random.Random(seed)
    sample = rng.sample(dataset, min(n, len(dataset)))

    auto_cols = [f"auto_label_{lbl}" for lbl in _ALL_LABELS]
    ann_cols = [f"annotation_{lbl}" for lbl in _ALL_LABELS]
    fieldnames = ["id", "text", "example_type"] + auto_cols + ann_cols

    with open(output_path, "w", encoding="utf-8-sig", newline="") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        for record in sample:
            record_labels = set(record.get("labels", []))
            row: dict[str, Any] = {
                "id": record.get("id", ""),
                "text": record.get("text", ""),
                "example_type": record.get("example_type", ""),
            }
            for lbl, col in zip(_ALL_LABELS, auto_cols):
                row[col] = 1 if lbl in record_labels else 0
            for col in ann_cols:
                row[col] = ""  # annotators fill this in
            writer.writerow(row)

    logger.info(
        "Annotation export: %d sentences → %s",
        len(sample), output_path,
    )
    logger.info(
        "Instructions: each annotator fills in annotation_{label} columns (0 or 1). "
        "Compute Cohen's Kappa when both annotators are done."
    )


def compute_cohen_kappa(
    annotator1_path: str | Path,
    annotator2_path: str | Path,
    output_path: str | Path | None = None,
) -> dict:
    """
    Compute per-label Cohen's Kappa from two filled annotation CSV files.

    Each CSV must have annotation_{label} columns (0 or 1) filled by one annotator.
    The same rows (same id order) must appear in both files.

    Parameters
    ----------
    annotator1_path:
        CSV filled by annotator 1 (annotation_{label} columns).
    annotator2_path:
        CSV filled by annotator 2 (annotation_{label} columns).
    output_path:
        Where to write kappa_results.json (defaults to config.KAPPA_RESULTS_PATH).

    Returns
    -------
    dict mapping label -> kappa float, plus "macro_avg" key.
    """
    from src.config import KAPPA_RESULTS_PATH

    output_path = Path(output_path) if output_path else KAPPA_RESULTS_PATH

    def _read_csv(path: Path) -> dict[str, list[int]]:
        result: dict[str, list[int]] = {lbl: [] for lbl in _ALL_LABELS}
        with open(path, encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                for lbl in _ALL_LABELS:
                    col = f"annotation_{lbl}"
                    val_str = row.get(col, "").strip()
                    try:
                        result[lbl].append(int(val_str))
                    except (ValueError, TypeError):
                        pass  # skip empty / invalid cells
        return result

    ann1 = _read_csv(Path(annotator1_path))
    ann2 = _read_csv(Path(annotator2_path))

    def _kappa(a: list[int], b: list[int]) -> float:
        n = min(len(a), len(b))
        if n == 0:
            return float("nan")
        a, b = a[:n], b[:n]
        p_o = sum(x == y for x, y in zip(a, b)) / n
        p_a1, p_a2 = sum(a) / n, sum(b) / n
        p_e = p_a1 * p_a2 + (1 - p_a1) * (1 - p_a2)
        if p_e >= 1.0:
            return 1.0
        return round((p_o - p_e) / (1 - p_e), 4)

    results: dict[str, float] = {}
    valid: list[float] = []
    for lbl in _ALL_LABELS:
        k = _kappa(ann1[lbl], ann2[lbl])
        results[lbl] = k
        if k == k:  # skip NaN
            valid.append(k)

    results["macro_avg"] = round(sum(valid) / len(valid), 4) if valid else float("nan")

    logger.info("Cohen's Kappa per label:")
    for lbl in _ALL_LABELS:
        logger.info("  %-30s κ = %.4f", lbl, results[lbl])
    logger.info("  %-30s κ = %.4f  (macro average)", "MACRO", results["macro_avg"])

    with open(output_path, "w", encoding="utf-8-sig") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)

    return results
